language: node_js
node_js:
  - "node"

before_install:
  - wget https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
  - unzip awscli-bundle.zip
  - ./awscli-bundle/install -b ~/bin/aws
  - export PATH=~/bin:$PATH

install:
  - npm install

script:
  - npm run build
  - npm run check-types
  - npm test

after_success:
  - mkdir -p .latest .all
  - cp -n dist/widgets.*.js .latest/
  - cp -n dist/styles.*.min.css .latest/

  - export AWS_ACCESS_KEY_ID=$AWS_S3_ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$AWS_S3_SECRET_KEY
  - export AWS_DEFAULT_REGION=eu-central-1
  - aws s3 sync s3://wsb-integrations .all
  - cp -n dist/widgets.*.js .all/
  - cp -n dist/styles.*.min.css .all/


deploy:
  - provider: s3
    access_key_id: $AWS_S3_ACCESS_KEY
    secret_access_key: $AWS_S3_SECRET_KEY
    skip_cleanup: true
    local_dir: .latest
    bucket: wsb-integrations
    on:
      all_branches: true
      tags: true

  - provider: surge
    project: ./.all/
    domain: cdn.workshopbutler.com
    skip_cleanup: true
    on:
      all_branches: true
      tags: true

