on:
  release:
    types: [created]

env:
  NODE_VERSION: '10.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project
        npm install
        npm run build
        npm run check-types
        npm run check-ts-styles
        npm run test
    - name: 'Deploy to AWS'
      run:
        echo "Deploy process should be here"
